### ISSUE TITLE
Error while hosting to vercel through github

### ISSUE THREAD

**Issue by SuperSmokerScope** [AntonioErdeljac/next13-airbnb-clone#13]
*************************************************************************
<html>
<body>

PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
--
18:15:56.911 |  
18:15:56.914 | Learn how: https://pris.ly/d/vercel-build
18:15:56.914 | at checkPlatformCaching (/vercel/path0/node_modules/@prisma/client/runtime/library.js:166:69)
18:15:56.915 | at new PrismaClient (/vercel/path0/node_modules/@prisma/client/runtime/library.js:179:3374)
18:15:56.915 | at 61306 (/vercel/path0/.next/server/chunks/627.js:141:37)
18:15:56.915 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
18:15:56.915 | at 77561 (/vercel/path0/.next/server/app/api/listings/route.js:192:16)
18:15:56.916 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
18:15:56.922 | at __webpack_exec__ (/vercel/path0/.next/server/app/api/listings/route.js:283:39)
18:15:56.923 | at /vercel/path0/.next/server/app/api/listings/route.js:284:78
18:15:56.923 | at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:150:21)
18:15:56.923 | at /vercel/path0/.next/server/app/api/listings/route.js:284:47 {
18:15:56.923 | clientVersion: '4.13.0',
18:15:56.924 | errorCode: undefined
18:15:56.926 | }
18:15:56.927 |  
18:15:56.928 | > Build error occurred
18:15:56.928 | Error: Failed to collect page data for /api/listings
18:15:56.928 | at /vercel/path0/node_modules/next/dist/build/utils.js:1062:15
18:15:56.928 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
18:15:56.929 | type: 'Error'
18:15:56.929 | }
18:15:57.139 | Error: Command "npm run build" exited with 1
18:15:57.440 | Deployment completed
18:15:57.393 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

</body>
</html>
****************************************************

Im getting this error while deploying this air bnb project to vercel. I did everything accordingly how Antonio said in that video.
I checked twice by running 'npm run lint'. And there are no errors after executing this command. Im still not getting why this error is happening. If anyone knows how to fix this, kindly please reply back.
  ThankYou

**Comment by rushikesh611** [comment]
You can try one of the given methods.
https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/vercel-caching-issue

I updated build script field in vercel with prisma generate. Works fine.

**Comment by SuperSmokerScope** [comment]
Oh, I forgot to update. Actually I solved all the issues through a lot of research.  Anyways thankyou for your quick response
