### ISSUE TITLE
I there a way to make all modal state in one state?

### ISSUE THREAD

**Issue by zougari47** [AntonioErdeljac/next13-airbnb-clone#24]
I'm wondering if will be a possible way to make one hook that handles all modal's states instead of creating a state for each one.

**Comment by hongk-bb** [comment]
This is my code. When adding modals in the future, you only need to add them in storeNames.

```
/* app/hooks/useModalStore.ts */

import create from "zustand"

interface ModalStore {
  isOpen: boolean
  onOpen: () => void
  onClose: () => void
}

type ModalStores = Record<string, ModalStore>

const storeNames = ["loginModal", "registerModal", "rentModal", "searchModal"]

const useModalStore = create<ModalStores>(set => {
  const stores: ModalStores = {}

  // Define the onOpen and onClose functions outside the ModalStore object
  const onOpen = (name: string) => {
    set(state => ({ ...state, [name]: { ...state[name], isOpen: true } }))
  }

  const onClose = (name: string) => {
    set(state => ({ ...state, [name]: { ...state[name], isOpen: false } }))
  }

  storeNames.forEach(name => {
    stores[name] = {
      isOpen: false,
      onOpen: () => onOpen(name),
      onClose: () => onClose(name)
    }
  })
  return stores
})

export default useModalStore
```

This code defines a Zustand store using the create function. The store manages a collection of modals, where each modal has an isOpen flag and onOpen and onClose functions.

The storeNames array contains the names of the modals to be managed by the store. The useModalStore hook creates a ModalStores object, and for each name in storeNames, it creates a ModalStore object with the initial state and the updated onOpen and onClose functions. These functions create a new ModalStore object with the updated isOpen flag and the same onOpen and onClose functions, and then merge it with the existing state using the object spread syntax.

The create function returns the useModalStore hook, which can be used in your code like this:

```
import useModalStore from "@/app/hooks/useModalStore";

const { loginModal, registerModal, rentModal, searchModal } = useModalStore();

loginModal.onOpen(); // opens the login modal
registerModal.isOpen; // returns false (assuming it hasn't been opened yet)
rentModal.onClose(); // closes the rent modal
searchModal.isOpen = true; // opens the search modal
```

Maybe this can help you.

**Comment by zougari47** [comment]
I tried it and it works 🎉 

I think is better practice if you have a lot of modals. Thank you.
