### ISSUE TITLE
Prerendering Error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Takeru9016** [AntonioErdeljac/next13-airbnb-clone#27]
>Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at /home/takeru9016/Projects/airbnb-clone/.next/server/chunks/118.js:33080:19
    at /home/takeru9016/Projects/airbnb-clone/.next/server/chunks/118.js:32858:11
    at 21227 (/home/takeru9016/Projects/airbnb-clone/.next/server/chunks/118.js:32860:3)
    at __webpack_require__ (/home/takeru9016/Projects/airbnb-clone/.next/server/webpack-runtime.js:25:43)
    at 88605 (/home/takeru9016/Projects/airbnb-clone/.next/server/chunks/885.js:1444:65)
    at __webpack_require__ (/home/takeru9016/Projects/airbnb-clone/.next/server/webpack-runtime.js:25:43)
    at 97368 (/home/takeru9016/Projects/airbnb-clone/.next/server/chunks/885.js:2944:63)
    at __webpack_require__ (/home/takeru9016/Projects/airbnb-clone/.next/server/webpack-runtime.js:25:43)
    at 35131 (/home/takeru9016/Projects/airbnb-clone/.next/server/chunks/885.js:118:69)
    at __webpack_require__ (/home/takeru9016/Projects/airbnb-clone/.next/server/webpack-runtime.js:25:43)

> Export encountered errors on following paths:
        /favorites/page: /favorites
        /page: /
        /properties/page: /properties
        /reservations/page: /reservations
        /trips/page: /trips

Description: 
I encountered a prerendering error while running my Next.js application. The error message states: "ReferenceError: window is not defined." This error occurs during the process of generating static pages, specifically when prerendering the pages "/" (homepage), "/favorites", "/reservations", "/properties", and "/trips".

I have followed the link provided in the error message (https://nextjs.org/docs/messages/prerender-error) to gather more information, but I couldn't find a specific solution for this issue.

It seems that the error is related to the usage of the window object in a server-side context. The window object is only available in the browser environment and not in the Node.js environment used during server-side rendering.

I would appreciate any guidance or suggestions on how to resolve this error and successfully prerender these pages in my Next.js application.

**Comment by llallallall** [comment]
'error.tsx ' cause the error. just remove it or replace like below

`'use client' // Error components must be Client Components

import { useEffect } from 'react'

export default function Error({
        error,
        reset,
}: {
        error: Error
        reset: () => void
}) {
        useEffect(() => {
                // Log the error to an error reporting service
                console.error(error)
        }, [error])

        return (
                <div
                        className="h-[60vh]
                                flex flex-col gap-2
                                justify-center
                                items-center">
                        <div className="text-center">
                                <div className="text-2xl font-bold">Uh Oh</div>
                                <div className="font-light text-neutral-500 mt-2">
                                        Something went wrong!
                                </div>
                        </div>
                        <div
                                className="w-48 mt-4
                                
                        ">
                                <button
                                        onClick={
                                                // Attempt to recover by trying to re-render the segment
                                                () => reset()
                                        }
                                        className=" 
                                        relative
                                        disabled:opacity-70
                                        disabled:cursor-not-allowed
                                        rounded-lg
                                        hover:opacity-80
                                        transition
                                        w-full
                                       bg-white
                                       border-black
                                       text-black
                                       ">
                                        Reset
                                </button>
                        </div>
                </div>
        )
}
`

**Comment by Takeru9016** [comment]
Thanks it worked !
