### ISSUE TITLE
DEPLOY ERROR

### ISSUE THREAD

**Issue by KChakhalyan** [AntonioErdeljac/next13-airbnb-clone#50]
Failed to compile.
--
02:41:57.297 |  
02:41:57.297 | ./app/listings/[listingId]/page.tsx:27:25
02:41:57.297 | Type error: Type '{ createdAt: string; user: { createdAt: string; updatedAt: string; emailVerified: (() => string) \| null; id: string; name: string \| null; email: string \| null; image: string \| null; hashedPassword: string \| null; favoriteIds: string[]; id_token: string \| null; }; ... 10 more ...; price: number; }' is not assignable to type 'Omit<{ id: string; title: string; description: string; imageSrc: string; createdAt: Date; category: string; roomCount: number; bathroomCount: number; guestCount: number; locationValue: string; userId: string; price: number; }, "createdAt"> & { ...; } & { ...; }'.
02:41:57.297 | Type '{ createdAt: string; user: { createdAt: string; updatedAt: string; emailVerified: (() => string) \| null; id: string; name: string \| null; email: string \| null; image: string \| null; hashedPassword: string \| null; favoriteIds: string[]; id_token: string \| null; }; ... 10 more ...; price: number; }' is not assignable to type '{ user: SafeUser; }'.
02:41:57.298 | Types of property 'user' are incompatible.
02:41:57.298 | Type '{ createdAt: string; updatedAt: string; emailVerified: (() => string) \| null; id: string; name: string \| null; email: string \| null; image: string \| null; hashedPassword: string \| null; favoriteIds: string[]; id_token: string \| null; }' is not assignable to type 'SafeUser'.
02:41:57.298 | Type '{ createdAt: string; updatedAt: string; emailVerified: (() => string) \| null; id: string; name: string \| null; email: string \| null; image: string \| null; hashedPassword: string \| null; favoriteIds: string[]; id_token: string \| null; }' is not assignable to type '{ createdAt: string; updatedAt: string; emailVerified: string \| null; }'.
02:41:57.298 | Types of property 'emailVerified' are incompatible.
02:41:57.298 | Type '(() => string) \| null' is not assignable to type 'string \| null'.
02:41:57.298 | Type '() => string' is not assignable to type 'string'.
02:41:57.298 |  
02:41:57.298 | 25 \|    return (
02:41:57.298 | 26 \|       <ClientOnly>
02:41:57.299 | > 27 \|          <ListingClient listing={listing} currentUser={currentUser} reservations={reservations} />
02:41:57.299 | \|                         ^
02:41:57.299 | 28 \|       </ClientOnly>
02:41:57.299 | 29 \|    );
02:41:57.299 | 30 \| };
02:41:57.421 | Error: Command "npm run build" exited with 1

### **_ANY SUGGESTIONS?_**

![Screenshot 2023-09-08 at 03 08 30](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/10487372/8c83cb3a-129b-4762-be7a-4a0b1047c865)
![Screenshot 2023-09-08 at 03 00 59](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/10487372/fdb514d4-27b7-44ea-b69b-04bb6c01d5d3)

**Comment by shawon-talukder** [comment]
Assuming you followed the tutorial, in your types/index.ts check your 'SafeUser' formatting.  Hope this will fix the error.
![image](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/80114074/e26d4c78-3a23-4ee0-bc67-63b55de47e40)
