### ISSUE TITLE
individual listing error

### ISSUE THREAD

**Issue by ShreyasLakhani** [AntonioErdeljac/next13-airbnb-clone#52]
![image](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/105536945/770c1377-62df-40a0-b5bc-0c65869656f1)
![image](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/105536945/2c47bc7e-2fee-4252-b998-6c66663f46fe)

![image](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/105536945/ba76a767-6ea6-4528-a3e8-ad86954cba81)

when i click any image at that time error throw

**Comment by ngoc2003** [comment]
Have u fixed it yet? @ShreyasLakhani

**Comment by abhisheksahu2001** [comment]
i added optional chaining before toString()  in getListingById function return statement
