### ISSUE TITLE
404 api/listings NOT FOUND

### ISSUE THREAD

**Issue by BlerionMuco** [AntonioErdeljac/next13-airbnb-clone#69]
Hello everyone i am facing a problem

I am trying to create a listings but I get /api/listings call 404
Anyone knows the problem?

Thanks
![Screenshot 2023-10-21 at 11 07 52 AM](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/66955735/8b225bf8-3465-4589-b261-1645fda2bb51)

**Comment by ShafiaAnsar** [comment]
did you solve that error? I'm getting same error

**Comment by BlerionMuco** [comment]
@ShafiaAnsar yes, i was missing a file on app/actions/getListings.ts
Please check the github repository
